name: CI - Build & Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Connexion à Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build de l’image Docker
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/gestion_compte:latest .

      - name: Push de l’image vers Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/gestion_compte:latest

